rzzx_logstash_service:
  container_name: rzzx_logstash
  image: rzzx_logstash
  ports:
    - "5045:5044" 
  #environment:
  volumes:
    - ./logstash_config/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash_config/conf.d/:/usr/share/logstash/pipeline/
    - ./logstash_config/patterns/:/usr/share/logstash/patterns/ 
